name: py

on:
  workflow_dispatch:
    inputs:
      file:
        required: true
        type: string

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          time python ${{ inputs.file }}
